from pathlib import Path


def _as_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, dict):
        return [f"{k}: {v}" for k, v in value.items()]
    return [value]


def node_markdown(node):
    d = node.data
    lines = [
        f"# {node.title}",
        "",
        f"**ID:** `{node.id}`",
        f"**Kind:** `{node.kind}`",
        "",
        "## Purpose",
        "",
        d.get("purpose", "This specification is generated from Knowledge Source Language."),
        "",
    ]
    for key in ["confidence", "status", "source", "summary", "severity", "rule"]:
        if d.get(key):
            lines += [f"**{key.title()}:** {d[key]}", ""]
    if d.get("ownership"):
        lines += ["## Ownership Contract", ""]
        for k, v in d["ownership"].items():
            lines += [f"### {k}", ""]
            lines += [*(f"- `{x}`" for x in _as_list(v)), ""]
    for key, title in [
        ("owns", "Owns"), ("references", "References"), ("contains", "Contains"),
        ("uses", "Uses"), ("constraints", "Constraints"), ("ai_rules", "AI Rules"),
        ("anti_patterns", "Anti-patterns"), ("validation", "Validation"),
        ("steps", "Steps"), ("failure_modes", "Failure Modes"), ("recovery", "Recovery"),
        ("metrics", "Metrics"), ("expected", "Expected"), ("prevents", "Prevents"),
    ]:
        vals = _as_list(d.get(key))
        if vals:
            lines += [f"## {title}", "", *(f"- {x}" for x in vals), ""]
    if node.links:
        lines += ["## Knowledge Links", ""]
        lines += [*(f"- `{l['type']}` → `{l['target']}`" for l in node.links), ""]
    return "\n".join(lines).strip() + "\n"


def write_markdown(project, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    index = []
    for node in project.nodes:
        sub = node.kind.upper()
        filename = f"{node.id.lower().replace('_', '-').replace(':', '-')}.md"
        p = out_dir / sub / filename
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(node_markdown(node), encoding="utf-8")
        index.append((node.title, p.relative_to(out_dir).as_posix(), node.id))
    home = out_dir / "index.md"
    home.write_text(
        "# Repository Index\n\nGenerated by **Knowledge OS / PKC v0.6.0**.\n\n"
        + "\n".join(f"- [{t}]({path}) `{i}`" for t, path, i in index)
        + "\n",
        encoding="utf-8",
    )
    return index
