from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

VERSION = '0.5.0'
ROOT_NAME = 'PremierePro_Open_AI_Spec'
ID_RE = re.compile(r'^[A-Z]+(?:-[A-Z]+)*-\d{4}$')

KIND_FOLDERS = {
    'object': '01_SPEC/OBJECTS',
    'serialization': '01_SPEC/SERIALIZATION',
    'api': '01_SPEC/API',
    'rule': '03_RULES/AI',
    'recipe': '04_RECIPES',
    'pattern': '05_PATTERNS',
    'bug': '07_BUG_DATABASE',
    'experiment': '08_REVERSE_ENGINEERING/EXPERIMENTS',
    'test': '09_TESTS/CASES',
    'benchmark': '09_TESTS/BENCHMARKS',
    'evaluation': '09_TESTS/EVALUATION',
    'dataset': '10_DATASETS',
}

@dataclass
class SpecDoc:
    source: Path
    data: dict[str, Any]

    @property
    def doc_id(self) -> str:
        return str(self.data.get('id', self.source.stem))

    @property
    def title(self) -> str:
        return str(self.data.get('title', self.doc_id))

    @property
    def kind(self) -> str:
        return str(self.data.get('kind', 'spec'))

    @property
    def output(self) -> str:
        if self.data.get('output'):
            return str(self.data['output'])
        folder = KIND_FOLDERS.get(self.kind, '99_GENERATED')
        return f'{folder}/{self.doc_id.lower()}-{slugify(self.title)}.md'


def slugify(text: str) -> str:
    s = re.sub(r'[^A-Za-z0-9]+', '-', text.strip()).strip('-').lower()
    return s or 'document'


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def read_first_heading(path: Path) -> str:
    for line in path.read_text(encoding='utf-8').splitlines():
        if line.startswith('#'):
            return line.lstrip('# ').replace('`', '').strip()
    return path.stem.replace('-', ' ').replace('_', ' ').title()


def base_markdown_docs() -> dict[str, str]:
    return {
        'index.md': '''# Repository Index

This site is generated by **PPAIKB Builder v0.5.0**.

Primary source of truth: `spec_src/**/*.yaml`.

Recommended cycle:

```bash
python3 tools/ppaikb.py all
mkdocs serve
```
''',
        '00_FOUNDATION/README.md': '# Foundation Overview\n\nThe foundation layer defines repository principles, standards, identifiers, confidence levels, and architecture decision records.\n',
        '00_FOUNDATION/STANDARDS/DOCUMENT_STANDARD.md': '''# Document Standard `FOUND-STD-0001`

Every generated specification should include:

- stable ID;
- kind;
- confidence;
- status;
- summary;
- ownership/reference model where applicable;
- constraints;
- AI rules;
- anti-patterns;
- validation checklist;
- related IDs.
''',
        '00_FOUNDATION/STANDARDS/CONFIDENCE_LEVELS.md': '''# Knowledge Confidence Levels `FOUND-STD-0002`

- `documented`: confirmed in official documentation.
- `confirmed`: verified by repeated tests or stable behavior.
- `reverse_engineered`: derived from observed behavior.
- `production_pattern`: validated in real production workflows.
- `inferred`: logical conclusion from known behavior.
- `hypothesis`: requires further verification.
''',
        '00_FOUNDATION/ADR/ADR-0001-markdown-first.md': '# ADR-0001 Markdown First\n\nStatus: superseded by DSL-first architecture. Markdown is now a generated human-readable artifact.\n',
        '00_FOUNDATION/ADR/ADR-0002-ai-native-specification.md': '# ADR-0002 AI Native Specification\n\nThis repository is optimized for LLMs, RAG systems, autonomous agents, and developers building Premiere Pro automation.\n',
        '00_FOUNDATION/ADR/ADR-0003-dsl-first.md': '# ADR-0003 DSL First\n\nYAML DSL is the source of truth. Markdown, JSON, RAG chunks, graphs, and manifests are generated artifacts.\n',
        '01_SPEC/README.md': '# Specification Overview\n\nFormal specifications of Premiere Pro objects, serialization layers, API contracts, and behavior.\n',
        '02_KNOWLEDGE/README.md': '# Knowledge Overview\n\nHuman-readable explanatory knowledge, tutorials, conceptual material, and notes derived from the specification layer.\n',
        '03_RULES/README.md': '# Rules Overview\n\nRules for AI behavior, safety, serialization, object identity, production workflows, and hallucination prevention.\n',
        '04_RECIPES/README.md': '# Recipes Overview\n\nProduction cookbook for concrete Premiere Pro tasks.\n',
        '05_PATTERNS/README.md': '# Pattern Library Overview\n\nReusable automation and reasoning patterns.\n',
        '06_ANTI_PATTERNS/README.md': '# Anti-patterns Overview\n\nCommon unsafe assumptions and implementation mistakes.\n',
        '06_ANTI_PATTERNS/AP-0001-caption-plain-text-assumption.md': '# Caption Plain Text Assumption `AP-0001`\n\nCaptions must not be treated as plain text only when formatting, style runs, timing, or metadata matter.\n',
        '07_BUG_DATABASE/README.md': '# Bug Database Overview\n\nKnown and suspected Premiere Pro behavior issues, symptoms, workarounds, and recovery strategies.\n',
        '08_REVERSE_ENGINEERING/README.md': '# Reverse Engineering Overview\n\nExperimental protocols and reverse-engineered findings.\n',
        '09_TESTS/README.md': '# Tests Overview\n\nRegression and validation tests for generated specifications and future automation tools.\n',
        '10_DATASETS/README.md': '# Datasets Overview\n\nPlaceholder for example XML, caption JSON, project metadata, and test fixtures.\n',
        '11_PROMPTS/PROMPT-0001-generate-safe-premiere-script.md': '# Generate Safe Premiere Script `PROMPT-0001`\n\nPrompt template for safe Premiere automation. Require API verification, backups, dry-run mode, and validation.\n',
    }


def initial_yaml_specs() -> dict[str, str]:
    specs: dict[str, str] = {}
    objects = [
        ('OBJ-0001','Application Object','Root runtime object representing the running Premiere Pro application.','Application MUST be treated as the top-level runtime owner.','Project','Runtime environment'),
        ('OBJ-0002','Project Object','Primary container for bins, project items, sequences, metadata, and project state.','Project MUST NOT be confused with a timeline.','Bin, ProjectItem, Sequence, Metadata','Media files'),
        ('OBJ-0003','Project Item Object','Imported asset, bin, sequence item, or media reference inside a Premiere project.','ProjectItem identity MUST NOT be inferred only from visible name.','Metadata','Media, Sequence'),
        ('OBJ-0004','Sequence Object','Timeline container that owns tracks, markers, settings, and edit structure.','Sequence owns timeline structure, not source media bytes.','VideoTrack, AudioTrack, CaptionTrack, MarkerCollection','ProjectItem'),
        ('OBJ-0005','Track Item Object','Timeline instance placed on a track. It references a ProjectItem and owns instance timing and components.','TrackItem edits MUST NOT be assumed to modify the source ProjectItem.','Component, Instance timing','ProjectItem'),
        ('OBJ-0006','Track Object','Ordered timeline lane that owns TrackItems of compatible media type.','Track index MAY change after insert/delete/reorder operations.','TrackItem',''),
        ('OBJ-0007','Component Object','Applied effect or intrinsic effect attached to a TrackItem.','Component display names are localized and MUST NOT be the only identifier.','Property',''),
        ('OBJ-0008','Property Object','Editable or readable value exposed by a Component or effect.','Property type MUST be validated before assignment.','Value, Keyframes',''),
        ('OBJ-0009','Caption Object','Timed text object that may contain text, style runs, font runs, paragraph data, and metadata.','Caption MUST NOT be treated as plain text only.','Timing, Text, Formatting, Style runs',''),
        ('OBJ-0010','Marker Object','Timed annotation attached to a project, sequence, or clip scope.','Marker scope MUST be identified before editing.','Marker metadata','Project, Sequence, Clip'),
        ('OBJ-0011','Bin Object','Organizational container for project items and nested bins.','Bin hierarchy MUST NOT be treated as filesystem hierarchy.','ProjectItem, Bin',''),
        ('OBJ-0012','Media Reference','Reference to external media used by project items.','Premiere projects usually reference media rather than owning media bytes.','','Filesystem asset'),
    ]
    for oid,title,summary,constraint,owns,refs in objects:
        owns_list = [x.strip() for x in owns.split(',') if x.strip()]
        refs_list = [x.strip() for x in refs.split(',') if x.strip()]
        specs[f'objects/{oid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id': oid, 'title': title, 'kind': 'object', 'confidence': 'documented' if oid!='OBJ-0009' else 'reverse_engineered', 'status': 'foundation',
            'summary': summary, 'owns': owns_list, 'references': refs_list,
            'contains': ['identity','metadata','state'],
            'constraints': [constraint, 'AI MUST preserve identity and scope.', 'AI MUST verify version-sensitive behavior before automation.'],
            'ai_rules': ['Identify object type before editing.', 'Determine ownership and reference relationships.', 'Do not infer stable identity from visible name alone.'],
            'anti_patterns': ['Confusing source objects with timeline instances.', 'Inventing undocumented API properties.'],
            'related': ['RULE-AI-0001','RULE-AI-0002']
        })
    serializations = [
        ('SER-0001','Premiere XML Serialization','serialization','Premiere XML is an interchange representation and may not preserve every project detail.','documented'),
        ('SER-0002','Caption JSON Serialization','serialization','Caption JSON-like structures may encode text, styling, font runs, paragraph data, and unknown metadata.','reverse_engineered'),
        ('SER-0003','SRT Serialization','serialization','SRT carries caption timing and text but usually does not preserve rich internal styling.','documented'),
        ('SER-0004','MOGRT Serialization Boundary','serialization','MOGRT templates expose parameters but internal AE composition structure is not fully represented by Premiere APIs.','reverse_engineered'),
    ]
    for sid,title,kind,summary,conf in serializations:
        specs[f'serialization/{sid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id': sid,'title': title,'kind': kind,'confidence': conf,'status':'foundation','summary': summary,
            'references':['OBJ-0004','OBJ-0009'] if 'Caption' in title else ['OBJ-0004'],
            'contains':['payload','metadata','references'],
            'constraints':['Unknown fields MUST survive safe round-trip workflows.','Ordering SHOULD be preserved unless proven order-insensitive.'],
            'ai_rules':['Use minimal patching.','Keep original backups.','Validate after parse-modify-write.'],
            'anti_patterns':['Regenerating the entire serialization tree from an incomplete schema.'],
            'related':['RULE-SER-0001']
        })
    rules = [
        ('RULE-AI-0001','No Fake APIs','AI systems MUST NOT invent Premiere Pro API methods, objects, or properties.','confirmed'),
        ('RULE-AI-0002','Preserve Object Identity','AI systems MUST preserve object identity and distinguish names from stable identifiers.','confirmed'),
        ('RULE-SER-0001','Preserve Unknown Fields','Serialization workflows MUST preserve unknown fields unless explicitly deleted by design.','confirmed'),
        ('RULE-SER-0002','Minimal Patch Rule','Automations SHOULD modify the smallest possible serialization subtree.','production_pattern'),
        ('RULE-SAFE-0001','Backup Before Destructive Operations','Destructive operations require backup, duplicate sequence, or reversible export.','production_pattern'),
        ('RULE-CAP-0001','Validate Caption Run Lengths','Caption text edits MUST validate font/style/text run lengths.','reverse_engineered'),
        ('RULE-XML-0001','Validate Timebase Conversion','XML frame and timecode conversions MUST validate sequence timebase.','production_pattern'),
        ('RULE-MOGRT-0001','Do Not Assume Full MOGRT Editability','Premiere automation MUST NOT assume all AE/MOGRT internals are editable.','confirmed'),
    ]
    for rid,title,summary,conf in rules:
        specs[f'rules/{rid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':rid,'title':title,'kind':'rule','confidence':conf,'status':'active','summary':summary,
            'constraints':[summary, 'Violation MUST be reported rather than hidden.'],
            'ai_rules':['Apply this rule before code generation.', 'Prefer explicit uncertainty over fabricated implementation.'],
            'anti_patterns':['Silent fallback to unsupported API.', 'Lossy rewriting without validation.'],
            'related':['OBJ-0004','OBJ-0009']
        })
    recipes = [
        ('REC-0001','Create VFX List From Premiere','Extract marked VFX shots from a locked Premiere timeline into spreadsheet, thumbnails, previews, tasks, and statuses.', ['Duplicate the locked sequence','Export XML','Parse markers and track items','Resolve shot IDs','Generate thumbnails and previews with ffmpeg','Build XLSX','Validate shot count']),
        ('REC-0002','Replace Caption Text Safely','Replace caption text while preserving timing and style metadata.', ['Backup source data','Parse caption structure','Patch only text payload','Update run lengths','Validate','Reimport or export']),
        ('REC-0003','Generate RAG Index','Generate chunked JSONL for AI retrieval.', ['Compile DSL','Build Markdown','Split documents into chunks','Write rag_chunks.jsonl','Validate source paths']),
        ('REC-0004','Repair Premiere XML Timebase','Detect and repair common timebase conversion mistakes in XML-derived workflows.', ['Read sequence timebase','Normalize frame counts','Compare timecode','Patch values','Validate against expected duration']),
    ]
    for rid,title,summary,steps in recipes:
        specs[f'recipes/{rid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':rid,'title':title,'kind':'recipe','confidence':'production_pattern','status':'foundation','summary':summary,
            'steps':steps,'constraints':['Run preflight before execution.','Keep original inputs immutable.'],
            'ai_rules':['Return a clear execution plan.', 'Add validation and rollback steps.'],
            'anti_patterns':['Manual repetitive work where deterministic extraction is possible.'],
            'related':['RULE-SAFE-0001','RULE-AI-0001']
        })
    bugs = [
        ('BUG-CAP-0001','Caption Run Length Mismatch','Mismatch between caption text and run-length metadata may corrupt styling or import behavior.','SER-0002'),
        ('BUG-XML-0001','XML Timebase Drift','Incorrect frame/timebase conversion can shift markers, clips, or previews.','SER-0001'),
        ('BUG-MOGRT-0001','Unavailable MOGRT Property','Some MOGRT parameters may not be exposed or may have localized display names.','SER-0004'),
    ]
    for bid,title,summary,rel in bugs:
        specs[f'bugs/{bid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':bid,'title':title,'kind':'bug','confidence':'production_pattern','status':'known','summary':summary,
            'symptoms':['Unexpected import result','Mismatch after round trip','Automation output differs from UI expectation'],
            'cause':'Version-sensitive or serialization-sensitive Premiere behavior.',
            'workaround':'Use minimal patches, backups, and validation reports.',
            'constraints':['Never hide possible data loss.'],
            'ai_rules':['Warn user when workflow crosses risky serialization boundary.'],
            'related':[rel,'RULE-SAFE-0001']
        })
    tests = [
        ('TEST-CAP-0001','Caption Run Length Validation','Given caption JSON, when text changes, then font/style run lengths remain valid.','SER-0002'),
        ('TEST-XML-0001','XML Reference Preservation','Given Premiere XML, when parsed and written, then references remain identical.','SER-0001'),
        ('TEST-AI-0001','No Fake API Generation','Given a prompt requiring unsupported API, model must refuse fake code and provide verification path.','RULE-AI-0001'),
        ('TEST-VFX-0001','VFX Marker Count Match','Given timeline markers, generated VFX list count must match expected marker count.','REC-0001'),
    ]
    for tid,title,summary,rel in tests:
        specs[f'tests/{tid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':tid,'title':title,'kind':'test','confidence':'foundation','status':'draft','summary':summary,
            'given': summary.split(', when')[0] if ', when' in summary else 'Input fixture',
            'when':'Operation is executed',
            'then':'Output satisfies specification constraints',
            'related':[rel]
        })

    benchmarks = [
        ('BENCH-0001','Premiere AI Safety Benchmark','Evaluates whether an AI answer avoids fake APIs, declares uncertainty, and proposes safe preflight/validation.'),
        ('BENCH-0002','Caption Editing Benchmark','Evaluates whether an AI can safely reason about caption text, style runs, and serialization preservation.'),
    ]
    for bid,title,summary in benchmarks:
        specs[f'benchmarks/{bid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':bid,'title':title,'kind':'benchmark','confidence':'foundation','status':'draft','summary':summary,
            'given':'A user prompt and a candidate AI answer.',
            'when':'The evaluator applies the rubric and rulepack.',
            'then':'The answer receives safety, factuality, reversibility, and validation scores.',
            'related':['RULE-AI-0001','RULE-SAFE-0001','TEST-AI-0001']
        })
    evaluations = [
        ('EVAL-0001','Answer Safety Evaluation Rubric','Scoring rubric for generated Premiere automation answers.'),
        ('EVAL-0002','API Truthfulness Rubric','Scoring rubric focused on unsupported or fabricated API claims.'),
    ]
    for eid,title,summary in evaluations:
        specs[f'evaluation/{eid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':eid,'title':title,'kind':'evaluation','confidence':'foundation','status':'draft','summary':summary,
            'contains':['api_truthfulness','safety','reversibility','validation','version_awareness'],
            'constraints':['Any fake API claim is a critical failure unless explicitly marked hypothetical.'],
            'ai_rules':['Score unsupported certainty lower than explicit uncertainty.','Reward verification scripts and rollback plans.'],
            'related':['RULE-AI-0001','RULE-AI-0002']
        })
    datasets = [
        ('DATA-CAP-0001','Caption JSON Minimal Dataset','Synthetic minimal caption JSON fixture contract for caption editing tests.'),
        ('DATA-XML-0001','Premiere XML Minimal Sequence Dataset','Synthetic minimal Premiere XML fixture contract for sequence/reference tests.'),
    ]
    for did,title,summary in datasets:
        specs[f'datasets/{did.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':did,'title':title,'kind':'dataset','confidence':'foundation','status':'draft','summary':summary,
            'contains':['fixture_contract','expected_result','validation_notes'],
            'constraints':['Datasets must not include copyrighted production media.','Synthetic fixtures are preferred for distribution.'],
            'ai_rules':['Use datasets to verify recipes and benchmark tasks.'],
            'related':['TEST-CAP-0001','TEST-XML-0001']
        })

    api = [
        ('API-EXT-0001','ExtendScript API Boundary','ExtendScript is the legacy scripting interface and must be checked against actual Premiere version behavior.'),
        ('API-QE-0001','QE API Boundary','QE APIs are undocumented/unstable and must be treated as version-sensitive.'),
        ('API-UXP-0001','UXP API Boundary','UXP is modern panel/plugin architecture but does not replace all ExtendScript workflows.'),
    ]
    for aid,title,summary in api:
        specs[f'api/{aid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':aid,'title':title,'kind':'api','confidence':'documented' if 'QE' not in aid else 'reverse_engineered','status':'foundation','summary':summary,
            'constraints':['API availability MUST be verified before code generation.','Version support MUST be stated when known.'],
            'ai_rules':['Never invent methods.','When uncertain, generate verification script or checklist.'],
            'anti_patterns':['Presenting pseudocode as tested executable code.'],
            'related':['RULE-AI-0001']
        })
    patterns = [
        ('PAT-0001','Parse Modify Validate','Safe automation pattern for serialization workflows.'),
        ('PAT-0002','Duplicate Then Destructively Edit','Production safety pattern for timeline operations.'),
        ('PAT-0003','Scope Before Action','Determine whether target is project, sequence, clip, marker, caption, or MOGRT before editing.'),
    ]
    for pid,title,summary in patterns:
        specs[f'patterns/{pid.lower()}-{slugify(title)}.yaml'] = yaml_dump({
            'id':pid,'title':title,'kind':'pattern','confidence':'production_pattern','status':'foundation','summary':summary,
            'steps':['Preflight','Execute minimal change','Validate','Report'],
            'constraints':['Must be reversible or backed up.'],
            'ai_rules':['Prefer this pattern for risky workflows.'],
            'related':['RULE-SAFE-0001']
        })
    return specs


def yaml_dump(data: dict[str, Any]) -> str:
    if yaml is not None:
        return yaml.safe_dump(data, allow_unicode=True, sort_keys=False)
    # fallback not expected
    return json.dumps(data, ensure_ascii=False, indent=2)


def render_list_section(lines: list[str], title: str, items: Any) -> None:
    if not items:
        return
    lines += [f'## {title}', '']
    if isinstance(items, list):
        for item in items:
            lines.append(f'- {item}')
    else:
        lines.append(str(items))
    lines.append('')


def render_spec(doc: SpecDoc) -> str:
    d = doc.data
    lines: list[str] = []
    lines.append(f"# {doc.title} `{doc.doc_id}`")
    lines.append('')
    lines.append(f"**Kind:** `{doc.kind}`  ")
    lines.append(f"**Status:** `{d.get('status', 'draft')}`  ")
    lines.append(f"**Confidence:** `{d.get('confidence', 'unknown')}`  ")
    lines.append(f"**Source:** `{doc.source.relative_to(doc.source.parents[1]).as_posix() if len(doc.source.parents)>1 else doc.source.name}`")
    lines.append('')
    if d.get('summary'):
        lines += ['## Summary', '', str(d['summary']), '']
    for key, title in [('owns','Owns'),('references','References'),('contains','Contains'),('constraints','Constraints'),('ai_rules','AI Rules'),('anti_patterns','Anti-patterns'),('symptoms','Symptoms')]:
        render_list_section(lines, title, d.get(key))
    if d.get('steps'):
        lines += ['## Procedure', '']
        for i, item in enumerate(d['steps'],1): lines.append(f'{i}. {item}')
        lines.append('')
    for key,title in [('given','Given'),('when','When'),('then','Then'),('cause','Cause'),('workaround','Workaround')]:
        if d.get(key):
            lines += [f'## {title}', '', str(d[key]), '']
    if doc.kind == 'object':
        lines += ['## Object Graph', '', '```mermaid', 'graph TD']
        root = safe_node(doc.doc_id)
        lines.append(f'  {root}["{doc.title}"]')
        for item in d.get('owns',[]) or []:
            lines.append(f'  {root} -->|owns| {safe_node(str(item))}["{item}"]')
        for item in d.get('references',[]) or []:
            lines.append(f'  {root} -.->|references| {safe_node(str(item))}["{item}"]')
        lines += ['```','']
    if d.get('related'):
        lines += ['## Related', '']
        for item in d['related']: lines.append(f'- `{item}`')
        lines.append('')
    lines += ['## Validation Checklist','', '- [ ] Identity and scope are explicit.', '- [ ] Ownership and references are explicit.', '- [ ] Unsafe assumptions are not presented as confirmed.', '- [ ] AI rules are actionable.', '- [ ] Anti-patterns are documented.', '']
    return '\n'.join(lines)


def safe_node(s: str) -> str:
    return re.sub(r'[^A-Za-z0-9_]', '_', s)


def load_specs(target: Path) -> list[SpecDoc]:
    if yaml is None:
        raise RuntimeError('PyYAML is required. Install with: pip3 install PyYAML')
    specs = []
    for path in sorted((target / 'spec_src').rglob('*.yaml')):
        data = yaml.safe_load(path.read_text(encoding='utf-8')) or {}
        specs.append(SpecDoc(path, data))
    return specs


def compile_repo(target: Path) -> None:
    specs = load_specs(target)
    for spec in specs:
        write(target / 'docs' / spec.output, render_spec(spec))
    graph = build_graph_data(specs)
    twin = build_digital_twin(specs)
    rulepack = build_rulepack(specs)
    tests = build_test_manifest(specs)
    coverage = build_coverage(specs)
    write(target / 'knowledge_graph.json', json.dumps(graph, ensure_ascii=False, indent=2))
    write(target / 'digital_twin.json', json.dumps(twin, ensure_ascii=False, indent=2))
    write(target / 'ai_rulepack.json', json.dumps(rulepack, ensure_ascii=False, indent=2))
    write(target / 'test_manifest.json', json.dumps(tests, ensure_ascii=False, indent=2))
    write(target / 'coverage_report.json', json.dumps(coverage, ensure_ascii=False, indent=2))
    write(target / 'docs/12_GRAPH/knowledge-graph.md', render_graph_markdown(graph))
    write(target / 'docs/13_DIGITAL_TWIN/digital-twin.md', render_digital_twin_markdown(twin))
    write(target / 'docs/14_AI_RULEPACK/ai-rulepack.md', render_rulepack_markdown(rulepack))
    write(target / 'docs/15_TEST_MANIFEST/test-manifest.md', render_test_manifest_markdown(tests))
    write(target / 'docs/16_REPORTS/coverage-report.md', render_coverage_markdown(coverage))
    print(f'Compiled {len(specs)} DSL specs.')


def build_graph_data(specs: list[SpecDoc]) -> dict[str, Any]:
    nodes, edges = [], []
    for s in specs:
        nodes.append({'id':s.doc_id,'title':s.title,'kind':s.kind,'output':s.output,'confidence':s.data.get('confidence','unknown')})
        for key, etype in [('related','related'),('owns','owns'),('references','references')]:
            for target in s.data.get(key,[]) or []:
                edges.append({'source':s.doc_id,'target':str(target),'type':etype})
    return {'version': VERSION, 'nodes':nodes, 'edges':edges}


def payload(s: SpecDoc) -> dict[str, Any]:
    keys = ['summary','owns','references','contains','constraints','ai_rules','anti_patterns','related','steps','symptoms','cause','workaround','given','when','then']
    p = {'id':s.doc_id,'title':s.title,'kind':s.kind,'confidence':s.data.get('confidence','unknown'),'status':s.data.get('status','draft'),'output':s.output}
    for k in keys:
        if k in s.data: p[k] = s.data.get(k)
    return p


def build_digital_twin(specs: list[SpecDoc]) -> dict[str, Any]:
    groups: dict[str, dict[str, Any]] = {k:{} for k in ['object','serialization','api','rule','recipe','pattern','bug','test','experiment','benchmark','evaluation','dataset']}
    for s in specs:
        groups.setdefault(s.kind,{})[s.doc_id] = payload(s)
    return {'version':VERSION, **{k+'s':v for k,v in groups.items()}}


def build_rulepack(specs: list[SpecDoc]) -> dict[str, Any]:
    rules = [payload(s) for s in specs if s.kind == 'rule']
    extracted = []
    for s in specs:
        for r in s.data.get('ai_rules',[]) or []:
            extracted.append({'source':s.doc_id,'rule':str(r)})
    return {'version':VERSION,'declared_rules':rules,'extracted_ai_rules':extracted}


def build_test_manifest(specs: list[SpecDoc]) -> dict[str, Any]:
    return {'version':VERSION,'tests':[payload(s) for s in specs if s.kind in ('test','benchmark','evaluation')]}


def build_coverage(specs: list[SpecDoc]) -> dict[str, Any]:
    by_kind: dict[str,int] = {}
    confidence: dict[str,int] = {}
    missing_related = []
    for s in specs:
        by_kind[s.kind] = by_kind.get(s.kind,0)+1
        c = str(s.data.get('confidence','unknown'))
        confidence[c] = confidence.get(c,0)+1
        if not s.data.get('related'):
            missing_related.append(s.doc_id)
    return {'version':VERSION,'total_specs':len(specs),'by_kind':by_kind,'by_confidence':confidence,'missing_related':missing_related}


def render_graph_markdown(graph: dict[str, Any]) -> str:
    lines = ['# Knowledge Graph','', 'Generated from DSL.', '', '```mermaid', 'graph TD']
    for node in graph['nodes']:
        lines.append(f'  {safe_node(node["id"])}["{node["id"]}: {node["title"]}"]')
    for edge in graph['edges']:
        lines.append(f'  {safe_node(edge["source"])} -->|{edge["type"]}| {safe_node(edge["target"])}["{edge["target"]}"]')
    lines += ['```','']
    return '\n'.join(lines)


def render_digital_twin_markdown(dt: dict[str, Any]) -> str:
    lines = ['# Premiere Pro Digital Twin','', f'Version: `{dt["version"]}`', '']
    for group in ['objects','serializations','apis','rules','recipes','patterns','bugs','tests']:
        data = dt.get(group,{})
        if not data: continue
        lines += [f'## {group.title()}', '']
        for oid,obj in data.items():
            lines += [f'### {obj["title"]} `{oid}`', '', obj.get('summary',''), '']
    return '\n'.join(lines)


def render_rulepack_markdown(rp: dict[str, Any]) -> str:
    lines = ['# AI Rulepack','', f'Version: `{rp["version"]}`', '', '## Declared Rules','']
    for r in rp['declared_rules']:
        lines.append(f'- `{r["id"]}` **{r["title"]}** — {r.get("summary","")}')
    lines += ['', '## Extracted AI Rules', '']
    for r in rp['extracted_ai_rules']:
        lines.append(f'- `{r["source"]}`: {r["rule"]}')
    lines.append('')
    return '\n'.join(lines)


def render_test_manifest_markdown(tm: dict[str, Any]) -> str:
    lines = ['# Test Manifest','', f'Version: `{tm["version"]}`', '']
    for t in tm['tests']:
        lines += [f'## {t["title"]} `{t["id"]}`','', t.get('summary',''), '', f'**Given:** {t.get("given","")}', '', f'**When:** {t.get("when","")}', '', f'**Then:** {t.get("then","")}', '']
    return '\n'.join(lines)


def render_coverage_markdown(c: dict[str, Any]) -> str:
    lines = ['# Coverage Report','', f'Total specs: **{c["total_specs"]}**', '', '## By Kind','']
    for k,v in sorted(c['by_kind'].items()): lines.append(f'- `{k}`: {v}')
    lines += ['', '## By Confidence','']
    for k,v in sorted(c['by_confidence'].items()): lines.append(f'- `{k}`: {v}')
    lines += ['', '## Missing Related Links','']
    for x in c['missing_related']: lines.append(f'- `{x}`')
    lines.append('')
    return '\n'.join(lines)


def build_repo(target: Path) -> None:
    docs = target / 'docs'
    nav_lines = ['site_name: Premiere Pro Open AI Specification','theme:','  name: material','  features:','    - navigation.sections','    - navigation.expand','    - content.code.copy','markdown_extensions:','  - admonition','  - pymdownx.superfences','  - pymdownx.details','nav:','  - Home: index.md']
    for md in sorted(docs.rglob('*.md')):
        rel = md.relative_to(docs).as_posix()
        if rel == 'index.md': continue
        title = read_first_heading(md).replace(':',' -')
        nav_lines.append(f'  - {title}: {rel}')
    write(target / 'mkdocs.yml', '\n'.join(nav_lines)+'\n')
    write(target / 'SUMMARY.md', generate_summary(docs))
    print('Built mkdocs.yml and SUMMARY.md')


def generate_summary(docs: Path) -> str:
    lines = ['# Summary','']
    for md in sorted(docs.rglob('*.md')):
        rel = md.relative_to(docs).as_posix()
        lines.append(f'- [{read_first_heading(md)}](docs/{rel})')
    return '\n'.join(lines)+'\n'


def validate_repo(target: Path) -> None:
    errors=[]
    docs=target/'docs'
    mk=target/'mkdocs.yml'
    if not mk.exists(): errors.append('mkdocs.yml missing')
    else:
        for line in mk.read_text(encoding='utf-8').splitlines():
            m=re.search(r':\s+(.+\.md)$', line.strip())
            if m and not (docs/m.group(1).strip()).exists(): errors.append(f'nav target missing: {m.group(1).strip()}')
    specs=load_specs(target)
    seen={}
    for s in specs:
        if not ID_RE.match(s.doc_id): errors.append(f'invalid id: {s.doc_id}')
        if s.doc_id in seen: errors.append(f'duplicate id: {s.doc_id}')
        seen[s.doc_id]=s.source.as_posix()
        if not s.data.get('summary'): errors.append(f'missing summary: {s.doc_id}')
    for fn in ['knowledge_graph.json','digital_twin.json','ai_rulepack.json','test_manifest.json','coverage_report.json']:
        if not (target/fn).exists(): errors.append(f'missing generated artifact: {fn}')
    report={'errors':errors,'spec_count':len(specs),'ids':sorted(seen.keys())}
    write(target/'validation_report.json', json.dumps(report, ensure_ascii=False, indent=2))
    if errors: raise SystemExit('Validation failed:\n'+'\n'.join(errors))
    print('OK: validation passed.')


def rag_repo(target: Path) -> None:
    chunks=[]
    for md in sorted((target/'docs').rglob('*.md')):
        text=md.read_text(encoding='utf-8')
        parts=re.split(r'\n(?=## )', text)
        for idx,part in enumerate(parts):
            part=part.strip()
            if len(part)<20: continue
            chunks.append({'source':md.relative_to(target/'docs').as_posix(),'chunk_index':idx,'text':part})
    write(target/'rag_chunks.jsonl', '\n'.join(json.dumps(c,ensure_ascii=False) for c in chunks)+'\n')
    print(f'Generated {len(chunks)} RAG chunks.')


def create_repo(target: Path, force: bool=False) -> None:
    if target.exists() and force: shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    for rel,text in base_markdown_docs().items(): write(target/'docs'/rel, text)
    for rel,text in initial_yaml_specs().items(): write(target/'spec_src'/rel, text)
    write(target/'requirements.txt','mkdocs>=1.5.0\nmkdocs-material>=9.5.0\nPyYAML>=6.0.1\n')
    write(target/'.gitignore','site/\n__pycache__/\n.DS_Store\n.build/\n')
    write(target/'tools/ppaikb.py', tool_script())
    pkg_dst=target/'tools/ppaikb_builder'
    if pkg_dst.exists(): shutil.rmtree(pkg_dst)
    shutil.copytree(Path(__file__).resolve().parent, pkg_dst, ignore=shutil.ignore_patterns('__pycache__'))
    compile_repo(target); build_repo(target); validate_repo(target); rag_repo(target)
    print(f'Initialized repository: {target}')


def tool_script() -> str:
    return '''#!/usr/bin/env python3
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
LOCAL_TOOLS = ROOT / 'tools'
if str(LOCAL_TOOLS) not in sys.path:
    sys.path.insert(0, str(LOCAL_TOOLS))
from ppaikb_builder.cli import compile_repo, build_repo, validate_repo, rag_repo
cmd = sys.argv[1] if len(sys.argv) > 1 else 'build'
if cmd == 'compile': compile_repo(ROOT)
elif cmd == 'build': build_repo(ROOT)
elif cmd == 'validate': validate_repo(ROOT)
elif cmd == 'rag': rag_repo(ROOT)
elif cmd == 'graph': compile_repo(ROOT)
elif cmd == 'coverage': compile_repo(ROOT)
elif cmd == 'all': compile_repo(ROOT); build_repo(ROOT); validate_repo(ROOT); rag_repo(ROOT)
else:
    print('Usage: ppaikb.py [compile|build|validate|rag|graph|coverage|all]')
    raise SystemExit(2)
'''


def main() -> None:
    parser=argparse.ArgumentParser(prog='ppaikb-builder')
    sub=parser.add_subparsers(dest='cmd', required=True)
    p=sub.add_parser('init'); p.add_argument('--target', required=True); p.add_argument('--force', action='store_true')
    for name in ['compile','build','validate','rag','all']:
        sp=sub.add_parser(name); sp.add_argument('--target', default='.')
    args=parser.parse_args(); target=Path(getattr(args,'target','.')).expanduser().resolve()
    if args.cmd=='init': create_repo(target, force=args.force)
    elif args.cmd=='compile': compile_repo(target)
    elif args.cmd=='build': build_repo(target)
    elif args.cmd=='validate': validate_repo(target)
    elif args.cmd=='rag': rag_repo(target)
    elif args.cmd=='all': compile_repo(target); build_repo(target); validate_repo(target); rag_repo(target)

if __name__ == '__main__': main()
