#!/usr/bin/env python3
"""OPS Knowledge Coverage Engine v0.1.

Builds a coverage report from OPS Knowledge Cards and the graph generated by
``tools/ops_graph.py``. The report is intentionally conservative: it measures
structural readiness, not factual correctness.

Outputs:
  build/coverage/coverage.json
  build/coverage/coverage.md

Commands:
  python3 tools/ops_coverage.py build
  python3 tools/ops_coverage.py validate
  python3 tools/ops_coverage.py summary
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

ROOT = Path.cwd()
ID_RE = re.compile(r"^[A-Z]+-[0-9]{4,}$")
DEFAULT_KNOWLEDGE_DIR = ROOT / "knowledge"
DEFAULT_OUT_DIR = ROOT / "build" / "coverage"

# Import sibling graph module without requiring package installation.
TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from ops_graph import build_graph, validate_graph  # noqa: E402


# Minimal readiness expectations by knowledge kind. These are intentionally
# weak for v0.1 so existing early-stage cards can be measured without being
# blocked. Stricter expectations should be added in future releases.
READINESS_EXPECTATIONS: Dict[str, Dict[str, List[str]]] = {
    "object": {
        "outgoing_relations_any": ["tested_by", "supported_by_evidence"],
    },
    "rule": {
        "outgoing_relations_any": ["tested_by", "supported_by_evidence"],
    },
    "capability": {
        "outgoing_relations_any": ["tested_by", "implemented_by_recipe", "supported_by_evidence"],
    },
    "recipe": {
        "outgoing_relations_any": ["supported_by_evidence"],
    },
    "test": {
        "incoming_relations_any": ["tested_by"],
    },
}

DOMAIN_KEYWORDS: Dict[str, List[str]] = {
    "object_model": ["object", "project", "sequence", "track", "media", "marker", "component"],
    "api": ["api", "extendscript", "uxp", "qe", "method", "property"],
    "caption": ["caption", "subtitle", "text run", "fontrun", "captiontrack"],
    "xml": ["xml", "serialization", "roundtrip", "fcpxml"],
    "production": ["vfx", "relink", "delivery", "turnover", "qc", "recipe", "production"],
    "safety": ["backup", "destructive", "preserve", "unknown", "identity", "safe"],
}


def _by_id(items: Iterable[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    return {str(item["id"]): item for item in items}


def _edges_by(graph: Dict[str, Any]) -> Tuple[Dict[str, List[Dict[str, Any]]], Dict[str, List[Dict[str, Any]]]]:
    outgoing: Dict[str, List[Dict[str, Any]]] = {}
    incoming: Dict[str, List[Dict[str, Any]]] = {}
    for edge in graph.get("edges", []):
        outgoing.setdefault(str(edge["source"]), []).append(edge)
        incoming.setdefault(str(edge["target"]), []).append(edge)
    return outgoing, incoming


def _count_by(items: Iterable[Dict[str, Any]], key: str) -> Dict[str, int]:
    result: Dict[str, int] = {}
    for item in items:
        value = str(item.get(key) or "unknown")
        result[value] = result.get(value, 0) + 1
    return dict(sorted(result.items()))


def _relation_set(edges: Iterable[Dict[str, Any]]) -> set[str]:
    return {str(edge.get("relation")) for edge in edges}


def _text_blob(node: Dict[str, Any]) -> str:
    return " ".join(str(node.get(k, "")) for k in ("id", "kind", "name", "summary", "path")).lower()


def compute_coverage(graph: Dict[str, Any]) -> Dict[str, Any]:
    nodes = list(graph.get("nodes", []))
    edges = list(graph.get("edges", []))
    nodes_by_id = _by_id(nodes)
    outgoing, incoming = _edges_by(graph)

    readiness: Dict[str, Dict[str, Any]] = {}
    issues: List[Dict[str, str]] = []

    for node in nodes:
        node_id = str(node["id"])
        kind = str(node.get("kind") or "unknown")
        expectations = READINESS_EXPECTATIONS.get(kind, {})
        node_out = outgoing.get(node_id, [])
        node_in = incoming.get(node_id, [])
        out_rel = _relation_set(node_out)
        in_rel = _relation_set(node_in)
        checks: List[Dict[str, Any]] = []

        for required_group in expectations.get("outgoing_relations_any", []):
            passed = required_group in out_rel
            checks.append({"check": f"outgoing:{required_group}", "passed": passed})
            if not passed:
                issues.append({
                    "severity": "warning",
                    "node": node_id,
                    "kind": kind,
                    "message": f"Missing outgoing relation '{required_group}'.",
                })

        for required_group in expectations.get("incoming_relations_any", []):
            passed = required_group in in_rel
            checks.append({"check": f"incoming:{required_group}", "passed": passed})
            if not passed:
                issues.append({
                    "severity": "warning",
                    "node": node_id,
                    "kind": kind,
                    "message": f"Missing incoming relation '{required_group}'.",
                })

        passed_count = sum(1 for c in checks if c["passed"])
        total_count = len(checks)
        score = 100 if total_count == 0 else round((passed_count / total_count) * 100, 2)
        readiness[node_id] = {
            "id": node_id,
            "kind": kind,
            "name": node.get("name"),
            "score": score,
            "checks_passed": passed_count,
            "checks_total": total_count,
            "outgoing_edges": len(node_out),
            "incoming_edges": len(node_in),
        }

    domains: Dict[str, Dict[str, Any]] = {}
    for domain, keywords in DOMAIN_KEYWORDS.items():
        matched = [n for n in nodes if any(keyword in _text_blob(n) for keyword in keywords)]
        domain_node_ids = {str(n["id"]) for n in matched}
        domain_scores = [readiness[nid]["score"] for nid in domain_node_ids if nid in readiness]
        domains[domain] = {
            "nodes": len(domain_node_ids),
            "average_readiness": round(sum(domain_scores) / len(domain_scores), 2) if domain_scores else 0,
            "node_ids": sorted(domain_node_ids),
        }

    orphan_nodes = []
    for node in nodes:
        node_id = str(node["id"])
        if not outgoing.get(node_id) and not incoming.get(node_id):
            orphan_nodes.append(node_id)

    critical_issues: List[Dict[str, str]] = []
    for target in graph.get("missing_targets", []):
        # Non-ID targets such as free-form format names are reported by the
        # graph but are not fatal in v0.1. Strict validation is reserved for
        # OPS-style identifiers like TEST-0001 or OBJ-0001.
        if ID_RE.match(str(target)):
            critical_issues.append({
                "severity": "error",
                "node": str(target),
                "kind": "missing_target",
                "message": f"Graph references missing target '{target}'.",
            })

    report = {
        "schema": "ops.coverage.v1",
        "generated_by": "tools/ops_coverage.py",
        "summary": {
            "nodes": len(nodes),
            "edges": len(edges),
            "kinds": _count_by(nodes, "kind"),
            "relations": _count_by(edges, "relation"),
            "orphan_nodes": len(orphan_nodes),
            "warnings": len(issues),
            "errors": len(critical_issues),
        },
        "domains": domains,
        "readiness": dict(sorted(readiness.items())),
        "orphan_nodes": sorted(orphan_nodes),
        "issues": critical_issues + issues,
    }
    return report


def write_outputs(report: Dict[str, Any], out_dir: Path = DEFAULT_OUT_DIR) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "coverage.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    write_markdown(report, out_dir / "coverage.md")


def write_markdown(report: Dict[str, Any], path: Path) -> None:
    summary = report["summary"]
    lines = [
        "# OPS Knowledge Coverage Report",
        "",
        f"Nodes: **{summary['nodes']}**",
        f"Edges: **{summary['edges']}**",
        f"Errors: **{summary['errors']}**",
        f"Warnings: **{summary['warnings']}**",
        f"Orphan nodes: **{summary['orphan_nodes']}**",
        "",
        "## Nodes by Kind",
        "",
    ]
    for kind, count in summary["kinds"].items():
        lines.append(f"- `{kind}`: {count}")
    lines += ["", "## Edges by Relation", ""]
    for relation, count in summary["relations"].items():
        lines.append(f"- `{relation}`: {count}")
    lines += ["", "## Domain Readiness", ""]
    for domain, data in sorted(report["domains"].items()):
        lines.append(f"- `{domain}`: {data['nodes']} nodes, average readiness {data['average_readiness']}%")
    lines += ["", "## Lowest Readiness Nodes", ""]
    readiness = sorted(report["readiness"].values(), key=lambda x: (x["score"], x["id"]))
    for item in readiness[:20]:
        lines.append(f"- `{item['id']}` {item['name']} ({item['kind']}): {item['score']}%")
    if report["issues"]:
        lines += ["", "## Issues", ""]
        for issue in report["issues"][:100]:
            lines.append(f"- **{issue['severity']}** `{issue['node']}`: {issue['message']}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_coverage(report: Dict[str, Any]) -> int:
    errors = [i for i in report.get("issues", []) if i.get("severity") == "error"]
    if errors:
        for issue in errors:
            print(f"ERROR: {issue['message']}", file=sys.stderr)
        return 1
    print("OK: coverage validation passed.")
    return 0


def print_summary(report: Dict[str, Any]) -> None:
    summary = report["summary"]
    print("OPS coverage summary")
    print(f"Nodes: {summary['nodes']}")
    print(f"Edges: {summary['edges']}")
    print(f"Errors: {summary['errors']}")
    print(f"Warnings: {summary['warnings']}")
    print("Kinds:")
    for kind, count in summary["kinds"].items():
        print(f"  {kind}: {count}")


def build_report(knowledge_dir: Path = DEFAULT_KNOWLEDGE_DIR) -> Dict[str, Any]:
    graph = build_graph(knowledge_dir)
    return compute_coverage(graph)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="OPS Knowledge Coverage Engine")
    sub = parser.add_subparsers(dest="command", required=True)

    p_build = sub.add_parser("build")
    p_build.add_argument("--knowledge", default=str(DEFAULT_KNOWLEDGE_DIR))
    p_build.add_argument("--out", default=str(DEFAULT_OUT_DIR))

    p_validate = sub.add_parser("validate")
    p_validate.add_argument("--knowledge", default=str(DEFAULT_KNOWLEDGE_DIR))

    p_summary = sub.add_parser("summary")
    p_summary.add_argument("--knowledge", default=str(DEFAULT_KNOWLEDGE_DIR))

    args = parser.parse_args(argv)
    report = build_report(Path(args.knowledge))

    if args.command == "build":
        write_outputs(report, Path(args.out))
        print(f"Built coverage report: {report['summary']['nodes']} nodes, {report['summary']['edges']} edges")
        print(f"Output: {Path(args.out)}")
        return validate_coverage(report)
    if args.command == "validate":
        return validate_coverage(report)
    if args.command == "summary":
        print_summary(report)
        return validate_coverage(report)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
