from pathlib import Path
VERSION='0.7.0'

def _as_list(value):
    if value is None: return []
    if isinstance(value, list): return value
    if isinstance(value, dict): return [f'{k}: {v}' for k, v in value.items()]
    return [value]

def _section(lines, title, vals):
    vals=_as_list(vals)
    if vals:
        lines += [f'## {title}', '', *(f'- {x}' for x in vals), '']

def node_markdown(node):
    d=node.data
    lines=[f'# {node.title}','',f'**ID:** `{node.id}`',f'**Kind:** `{node.kind}`','']
    for key in ['status','confidence','source','severity']:
        if d.get(key): lines += [f'**{key.title()}:** {d[key]}','']
    lines += ['## Purpose','',d.get('purpose','This specification is generated from Knowledge Source Language.'),'']
    if d.get('summary'): lines += ['## Summary','',str(d.get('summary')),'']
    if d.get('rule'): lines += ['## Rule','',str(d.get('rule')),'']
    if d.get('ownership'):
        lines += ['## Ownership Contract','']
        for k,v in d['ownership'].items():
            lines += [f'### {k}','',*([f'- `{x}`' for x in _as_list(v)]),'']
    sections=[('owns','Owns'),('references','References'),('contains','Contains'),('uses','Uses'),('constraints','Constraints'),('ai_rules','AI Rules'),('anti_patterns','Anti-patterns'),('steps','Steps'),('failure_modes','Failure Modes'),('recovery','Recovery'),('validation','Validation'),('expected','Expected'),('metrics','Metrics'),('prevents','Prevents'),('related','Related')]
    for key,title in sections: _section(lines,title,d.get(key))
    if d.get('references'): _section(lines,'External / Source References',d.get('references'))
    if node.links:
        lines += ['## Knowledge Links','',*(f"- `{l['type']}` → `{l['target']}`" for l in node.links),'']
    lines += ['## Agent Notes','','- Treat this page as compiled output. Edit the YAML source, not this Markdown file.','- Machine-readable authority lives in `build/artifacts/knowledge_ast.json`.','']
    return '\n'.join(lines).strip()+'\n'

def write_markdown(project, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    index=[]
    for node in project.nodes:
        sub=node.kind.upper()
        filename=f"{node.id.lower().replace('_','-').replace(':','-')}.md"
        p=out_dir/sub/filename
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(node_markdown(node), encoding='utf-8')
        index.append((node.title,p.relative_to(out_dir).as_posix(),node.id,node.kind))
    by_kind={}
    for t,path,i,k in index: by_kind.setdefault(k,[]).append((t,path,i))
    text=f"# Repository Index\n\nGenerated by **Knowledge OS / PKC v{VERSION}**.\n\nPrimary source of truth: `spec_src/**/*.yaml`.\n\n"
    text += "## Agent Ingestion\n\n1. Run `python3 tools/pkc.py all`.\n2. Load `build/artifacts/knowledge_ast.json`.\n3. Load `build/artifacts/ai_rulepack.json`.\n4. Use `build/rag/rag_chunks.jsonl` for retrieval.\n\n"
    for kind in sorted(by_kind):
        text += f'## {kind.title()}\n\n'
        for t,path,i in by_kind[kind]: text += f'- [{t}]({path}) `{i}`\n'
        text += '\n'
    (out_dir/'index.md').write_text(text, encoding='utf-8')
    return [(t,p,i) for t,p,i,k in index]
